id: y_line
name: Track
name[zh]: 线路追踪
version: 1.0.1
author: MBUILD
icon: app.png
desc: Track
files:
  - assets\images\loading\00001.png
  - assets\images\loading\00002.png
  - assets\images\loading\00003.png
  - assets\images\loading\00004.png
  - assets\images\loading\00005.png
  - assets\images\loading\00006.png
  - assets\images\loading\00007.png
  - assets\images\loading\00008.png
  - assets\images\loading\00009.png
  - assets\images\loading\00010.png
  - assets\images\loading\00011.png
  - assets\images\loading\00012.png
  - assets\images\loading\00013.png
  - assets\images\loading\00014.png
  - assets\images\loading\00015.png
  - assets\images\loading\00016.png
  - assets\images\loading\00017.png
  - assets\images\loading\00018.png
  - assets\images\loading\00019.png
  - assets\images\loading\00020.png
  - assets\images\loading\00021.png
  - assets\images\loading\00022.png
  - assets\images\loading\00023.png
  - assets\images\loading\00024.png
  - assets\images\loading\00025.png
  - assets\images\loading\00026.png
  - assets\images\loading\00027.png
  - assets\images\loading\00028.png
  - assets\images\loading\00029.png
  - assets\images\loading\00030.png
  - assets\images\loading\00031.png
  - assets\images\loading\00032.png
  - assets\images\loading\00033.png
  - assets\images\loading\00034.png
  - assets\images\loading\00035.png
  - assets\images\loading\00036.png
  - assets\images\loading\00037.png
  - assets\images\loading\00038.png
  - assets\images\loading\00039.png
  - assets\images\loading\00040.png
  - assets\images\loading\00041.png
  - assets\images\loading\00042.png
  - assets\images\loading\00043.png
  - assets\images\loading\00044.png
  - assets\images\loading\00045.png
  - assets\images\loading\00046.png
  - assets\images\loading\00047.png
  - assets\images\loading\00048.png
  - assets\images\loading\00049.png
  - assets\images\loading\00050.png
  - assets\images\loading\00051.png
  - assets\images\loading\00052.png
  - assets\images\loading\00053.png
  - assets\images\loading\00054.png
  - assets\images\loading\00055.png
  - assets\images\loading\00056.png
  - assets\images\loading\00057.png
  - assets\images\loading\00058.png
  - assets\images\loading\00059.png
  - assets\images\loading\00060.png
  - assets\images\loading\00061.png
  - assets\images\loading\00062.png
  - assets\images\loading\00063.png
  - assets\images\loading\00064.png
  - assets\images\loading\00065.png
  - assets\images\loading\00066.png
  - assets\images\loading\00067.png
  - assets\images\loading\00068.png
  - assets\images\loading\00069.png
  - assets\images\loading\00070.png
  - assets\images\loading\00071.png
  - assets\images\loading\00072.png
  - assets\images\loading\00073.png
  - assets\images\loading\00074.png
  - assets\images\loading\00075.png
  - assets\images\loading\00076.png
  - assets\images\loading\00077.png
  - assets\images\loading\00078.png
  - assets\images\loading\00079.png
  - assets\images\box_bg.png
  - assets\images\box_bg2_active.png
  - assets\images\box_bg2.png
  - assets\images\box_border.png
  - assets\images\forget.png
  - assets\images\icon_back.png
  - assets\images\img_eye_close.png
  - assets\images\img_eye_open.png
  - assets\images\learning.png
  - assets\images\line_learning_btn.png
  - app.png
  - app.yaml
  - loading.py
  - main.py
