# MaixCDK architecture helpers (PLATFORM x ARCH)
# MAIX_ARCH: riscv64 | arm64 | (empty for host/other)
# CONFIG_ARCH_RISCV64 / CONFIG_ARCH_ARM64: mutually exclusive when set

if(NOT DEFINED MAIX_ARCH OR MAIX_ARCH STREQUAL "")
    # Infer from known platforms if not injected by project.py
    if(PLATFORM_MAIXCAM2 OR PLATFORM_RK3566)
        set(MAIX_ARCH "arm64")
    elseif(PLATFORM_MAIXCAM)
        set(MAIX_ARCH "riscv64")
    else()
        set(MAIX_ARCH "native")
    endif()
endif()

if(MAIX_ARCH STREQUAL "riscv64")
    set(CONFIG_ARCH_RISCV64 1)
    set(CONFIG_ARCH_ARM64 0)
    set(MAIX_ARCH_IS_RISCV64 1)
    set(MAIX_ARCH_IS_ARM64 0)
    set(MAIX_ELF_MACHINE "RISC-V")
elseif(MAIX_ARCH STREQUAL "arm64")
    set(CONFIG_ARCH_RISCV64 0)
    set(CONFIG_ARCH_ARM64 1)
    set(MAIX_ARCH_IS_RISCV64 0)
    set(MAIX_ARCH_IS_ARM64 1)
    set(MAIX_ELF_MACHINE "AArch64")
else()
    set(CONFIG_ARCH_RISCV64 0)
    set(CONFIG_ARCH_ARM64 0)
    set(MAIX_ARCH_IS_RISCV64 0)
    set(MAIX_ARCH_IS_ARM64 0)
    set(MAIX_ELF_MACHINE "")
endif()

message(STATUS "MAIX_ARCH: ${MAIX_ARCH}")

# Resolve a path that may contain ${MAIX_ARCH} or be given as (riscv64_path; arm64_path)
# Usage:
#   maix_select_arch_path(OUT_VAR "lib/${MAIX_ARCH}/libfoo.so")
#   maix_select_arch_path(OUT_VAR "lib/riscv64/libfoo.so" "lib/arm64/libfoo.so")
function(maix_select_arch_path out_var)
    set(argc ${ARGC})
    if(argc EQUAL 2)
        string(REPLACE "\${MAIX_ARCH}" "${MAIX_ARCH}" resolved "${ARGV1}")
        set(${out_var} "${resolved}" PARENT_SCOPE)
    elseif(argc EQUAL 3)
        if(MAIX_ARCH STREQUAL "riscv64")
            set(${out_var} "${ARGV1}" PARENT_SCOPE)
        elseif(MAIX_ARCH STREQUAL "arm64")
            set(${out_var} "${ARGV2}" PARENT_SCOPE)
        else()
            message(FATAL_ERROR "maix_select_arch_path: unsupported MAIX_ARCH=${MAIX_ARCH}")
        endif()
    else()
        message(FATAL_ERROR "maix_select_arch_path: need 1 path template or 2 arch-specific paths")
    endif()
endfunction()

# Append dynamic lib path selected by arch under component-relative paths
# Usage: maix_append_arch_dynamic_lib(ADD_DYNAMIC_LIB "lib/riscv64/libfoo.so" "lib/arm64/libfoo.so")
function(maix_append_arch_dynamic_lib list_var riscv64_path arm64_path)
    set(_list ${${list_var}})
    if(MAIX_ARCH STREQUAL "riscv64")
        list(APPEND _list "${riscv64_path}")
    elseif(MAIX_ARCH STREQUAL "arm64")
        list(APPEND _list "${arm64_path}")
    else()
        message(FATAL_ERROR "maix_append_arch_dynamic_lib: unsupported MAIX_ARCH=${MAIX_ARCH}")
    endif()
    set(${list_var} "${_list}" PARENT_SCOPE)
endfunction()

# Optional ELF machine check (no-op if readelf/file unavailable or path missing)
function(maix_assert_elf_arch libpath)
    if(NOT MAIX_ELF_MACHINE)
        return()
    endif()
    if(NOT EXISTS "${libpath}")
        return()
    endif()
    find_program(MAIX_READELF NAMES readelf llvm-readelf)
    if(MAIX_READELF)
        execute_process(
            COMMAND ${MAIX_READELF} -h "${libpath}"
            OUTPUT_VARIABLE _hdr
            ERROR_QUIET
            OUTPUT_STRIP_TRAILING_WHITESPACE
        )
        if(_hdr AND NOT _hdr MATCHES "Machine:[^\n]*${MAIX_ELF_MACHINE}")
            message(FATAL_ERROR "ELF arch mismatch for ${libpath}: expected ${MAIX_ELF_MACHINE} (MAIX_ARCH=${MAIX_ARCH})")
        endif()
    endif()
endfunction()

# Append sources from port/<platform>/<arch>/ if that directory exists
# Usage: maix_append_arch_port_srcs(ADD_SRCS "port/maixcam")
function(maix_append_arch_port_srcs list_var port_base)
    set(_list ${${list_var}})
    set(_arch_dir "${port_base}/${MAIX_ARCH}")
    if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/${_arch_dir}" AND IS_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}/${_arch_dir}")
        append_srcs_dir(_list "${_arch_dir}")
        message(STATUS "Appending arch port sources: ${_arch_dir}")
    endif()
    set(${list_var} "${_list}" PARENT_SCOPE)
endfunction()
