id: y_speech
name: Speech old
name[zh]: 语音识别(原离线版)
version: 1.0.0
author: MBUILD
icon: app.png
desc: 语音识别(原离线版)
files:
  - assets\images\back.png
  - assets\images\back2.png
  - assets\images\cancel_btn.png
  - assets\images\check.png
  - assets\images\close_btn.png
  - assets\images\confirm_btn.png
  - assets\images\del.png
  - assets\images\edit.png
  - assets\images\keywords.png
  - assets\images\list.png
  - assets\images\SolarBillListOutline.png
  - assets\images\SolarCheckCircleOutline.png
  - assets\images\SolarPenNewSquareOutline.png
  - assets\images\SolarSoundwaveLinear.png
  - assets\images\SolarUndoLeftRoundOutline.png
  - assets\images\sound.png
  - assets\images\speech_recognition_chinese.png
  - assets\pinyin.bin
  - assets\Unihan_Readings.txt
  - app.png
  - app.yaml
  - delete_popup.py
  - main_backup.py
  - main.py
  - pinyin.py
  - utils.py
